vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


